fix: issue #3
monad-devrel/monad-discord-auth pull request #6
Opened 2024-08-25 07:13 UTC by Veenoway

2024-08-27 18:12 UTC, portdeveloper requested changes
Thanks for the good work @Veenoway !

2024-08-27 18:12 UTC, portdeveloper commented on src/constants/monad_roles.ts
> +export const rolePriority: Role[] = [
This is good! But I believe that ranking roles might be a little bit of overdoing it as these roles do not have clear rankings.

So maybe what we should do here is to not differentiate between any role, and just show all the roles or at least full access.

If we are still sure to implement a ranking, we may want to do that in another PR 🙏

2024-08-27 18:12 UTC, portdeveloper commented on src/app/components/Home.tsx
> +    return "Oops, looks like you're not a NAD yet :(";
Maybe we should not be saying not a NAD if the user is not a member

2024-08-29 07:46 UTC, portdeveloper commented
Hey thanks for the changes!

Two little nitpicks from me:
Home.tsx line 33: (capitalization)
      `else if (roleNames.includes('full_access')) return `${successText} Full access`;`
should be 
      `else if (roleNames.includes('full_access')) return `${successText} full access`;`
      
      and
      
Home.tsx line 34: (pluralization)
      `else return `Oh! Looks like you're still a newbies`;`
should be 
      `else return `Oh! Looks like you're still a newbie`;`

2024-08-29 16:29 UTC, portdeveloper approved these changes
Thanks for the good work @Veenoway !

And sorry for being this nitpicky haha.

2024-08-29 17:18 UTC, Veenoway commented
> Thanks for the good work @Veenoway !
> 
> And sorry for being this nitpicky haha.

No Problem about it it's normal! 
Thank to let us the opportunity to help

2024-08-30 07:22 UTC, merged