Readme updated
monad-devrel/monad-discord-auth pull request #8
Opened 2024-08-30 14:29 UTC by DyxaDevelop

2024-09-02 15:44 UTC, DyxaDevelop commented
This PR makes the following changes to the README.md

- Added visual enhancements: logo and various badges (Discord, Twitter, GitHub, etc.).
- Expanded the Table of Contents with new sections and links.
- Updated project description with a focus on Discord OAuth2 integration and user data handling.
- Clarified prerequisites: added PostgreSQL, adjusted Node.js minimum version (14+).
- Expanded setup and run instructions, including dependency installation and environment variables.
- Added a section detailing available scripts (dev, build, start, etc.).
- Provided more detailed deployment steps for Vercel.
- Added a "Troubleshooting" section with common issue resolutions.

2024-09-03 17:22 UTC, portdeveloper requested changes
Looks good to me except few nitpicks here and there 👍

2024-09-03 17:22 UTC, portdeveloper commented on README.md
> +    <a href="https://x.com/monad_xyz">
Since this is a community project let's remove the x link for monad here

2024-09-03 17:22 UTC, portdeveloper commented on README.md
> +npm install -g pnpm
Let's have this as the first option! https://pnpm.io/installation

2024-09-03 18:10 UTC, portdeveloper commented on README.md
> +This project is licensed under the MIT License. See the [LICENSE](LICENSE.md) file for details.
Hey I think we don't have a LICENSE file yet, could you please add an MIT license or remove this part?

2024-09-04 19:11 UTC, portdeveloper requested changes
All is great but i have dropped one comment on one line!

2024-09-04 19:11 UTC, portdeveloper commented on LICENSE
> +Copyright (c) 2024 Monad Developers
Sorry for being nitpicky again but maybe we should change it to "Monad Developer Community"

2024-09-04 19:55 UTC, DyxaDevelop commented on LICENSE
> +Copyright (c) 2024 Monad Developers
No problem, everything should be perfect!

2024-09-05 06:38 UTC, portdeveloper approved these changes
LGTM! Thanks @DyxaDevelop !!!

2024-09-05 06:38 UTC, merged